//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable_GAs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiGiang
    {
        public int MaBG { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public string Phong { get; set; }
        public string MonHoc { get; set; }
        public string GiaoVien { get; set; }
        public string Lop { get; set; }
    
        public virtual GiaoVien GiaoVien1 { get; set; }
        public virtual Lop Lop1 { get; set; }
        public virtual MonHoc MonHoc1 { get; set; }
        public virtual Phong Phong1 { get; set; }
        public virtual ThoiGian ThoiGian1 { get; set; }
    }
}
