//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable_GAs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThoiGian()
        {
            this.BaiGiangs = new HashSet<BaiGiang>();
        }
    
        public int MaTG { get; set; }
        public string Buoi { get; set; }
        public string Thu { get; set; }
        public Nullable<int> TietBD { get; set; }
        public Nullable<int> TietKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiGiang> BaiGiangs { get; set; }
    }
}
